name: Update Last Modified Date

on:
  pull_request:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

jobs:
  update-date:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ github.head_ref || github.ref_name }}

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install python-dateutil

      - name: Configure Git 
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"

      - name: Update last modified date in Markdown files
        run: python .github/workflows/update_date.py

      - name: Commit and merge changes
        env:
          PR_BRANCH: ${{ github.head_ref || github.ref_name }}
          GIT_AUTHOR_NAME: github-actions[bot]
          GIT_AUTHOR_EMAIL: github-actions[bot]@users.noreply.github.com
          GIT_COMMITTER_NAME: github-actions[bot]
          GIT_COMMITTER_EMAIL: github-actions[bot]@users.noreply.github.com
        run: |
          # Ensure we're on the correct branch
          git switch -c "$PR_BRANCH" || git switch "$PR_BRANCH"
          
          # Stage and commit all changes (new, modified, deleted)
          git add -A
          git diff --staged --quiet || git commit -m "Update last modified date in Markdown files"
          
          # Pull and merge existing changes from remote
          git pull origin "$PR_BRANCH" --no-rebase
          
          # Push all changes to the PR branch
          git push origin "$PR_BRANCH"
